name: eco
description: "Aplikasi lingkungan dengan AI - scan, analisis, dan chatbot"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5

  # Local Storage (JWT token & auth state)
  shared_preferences: ^2.2.3

  # AI / Gemini
  google_generative_ai: ^0.4.7

  # Camera & Media
  camera: ^0.11.2
  image_picker: ^1.2.1

  # Location
  geolocator: ^14.0.3
  geocoding: ^3.0.0

  # Maps
  google_maps_flutter: ^2.12.0

  # Networking
  http: ^1.6.0

  # UI & Media
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2
  shimmer: ^2.0.0

  # Utilities
  intl: ^0.20.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.6
  uuid: ^4.5.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
